---
- name: check bond
  include: check_bond.yml
- name: run iperf client
  include: client.yml.yml
- name: run iperf server
  include: server.yml
  with_items: "{{ groups['iperf_server'] }}"
  when: inventory_hostname != item

