- name: running bench from all server towards {{ item }}
  shell: "iperf -c {{ item }}"
  register: output

- debug:
     msg: "{{ output.stdout_lines | last }}"

- name: debug
  set_fact:
    result: "{{ output.stdout_lines | last }}"
 
- name: debug
  debug: var=result
  run_once: yes

- name: Echo result into file.
  shell: echo {{ result }} >> test.txt
  delegate_to: localhost 

- name: Cut the bandwidth from the text file
  shell: cat test.txt | awk '{print $ 7}'
  register: numbers
  delegate_to: localhost  
 
- debug:
     msg: "{{ numbers }}"
  delegate_to: localhost

- name: print numbers var before calculating
  debug:
     msg: "{{ numbers.stdout_lines }}"
  delegate_to: localhost

- name: Calculate the numbers
  shell: cat test.txt | awk '{print $ 7}' | awk '{s+=$1} END {print s}'  
  delegate_to: localhost
  register: final_number
  run_once: yes

- name: debug the number
  debug:
     msg: "{{ final_number }}"
  run_once: yes
 
- name: debug the number
  debug:
     msg: "{{ final_number.stdout_lines }}"
  delegate_to: localhost
  run_once: yes

- name: Create empty file - summery.txt
  file: 
    path: /etc/ansible/summery.txt
    state: touch
    owner: root
    group: root
    mode: 0600
  delegate_to: localhost
  run_once: yes

- name: add the test result into the summery file
  blockinfile:
    path: /etc/ansible/summery.txt
    block: |
      {{ item[0] }} {{ item[1] }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item[0] }}"
  with_nested:
  - "{{ item }}"
  - "{{ final_number.stdout_lines }}"
  delegate_to: localhost

- name: Remove file (delete file)
  file:
    path: /etc/ansible/roles/test.txt
    state: absent
  delegate_to: localhost
  run_once: yes

- name: Compare it is lower then
  shell: echo "Failed because number is lower than expected"
  failed_when: "{{ item }} < 100"
  delegate_to: localhost
  with_items:
  - "{{ final_number.stdout_lines }}"
  run_once: yes
